# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField(max_length=10)),
                ('andharnumber', models.CharField(max_length=13)),
                ('showtime', models.TimeField()),
            ],
        ),
    ]
