# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-31 05:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_auto_20190331_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='password',
            field=models.CharField(default=datetime.datetime(2019, 3, 31, 5, 35, 25, 619435, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
