# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-31 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_userdata_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
