# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-31 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_auto_20190331_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
