# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-20 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='productclass',
            field=models.CharField(max_length=10),
        ),
    ]
